### PR TITLE
Enforce maximum number of jobs allowed in queue per dapp in the free …

### PR DESCRIPTION
**Pull request by porkchop**
…vs paid bandwidth tiers. As well as a per dapp max queue override capability

### CODE REVIEW

**Comment by quocle108** [comment]
LGTM

**Comment by porkchop** [comment]
Needs tests

**Comment by danielvo11** [comment]
I added commit to:
- allow self permission in setbwpayer action
- add setconfig action
- update unit test using qtest

**Comment by porkchop** [comment]
Yup LGTM

**Pull request merged**
